### ISSUE TITLE
Add customizable MX priority for multiple MX records

### ISSUE THREAD

**Issue by yswery** [yswery/PHP-DNS-SERVER#10]
Need to be able to set a custom priority for multiple MX records in the dns storage.
Currently this is hard coded for "10" as per: https://github.com/yswery/PHP-DNS-SERVER/blob/master/src/Server.php#L372

**Comment by samuelwilliams** [comment]
See PR #22

**Comment by yswery** [comment]
This is fantastic thanks for sorting this one out!
