### ISSUE TITLE
Make queries fire off PHP threads non blocking

### ISSUE THREAD

**Issue by yswery** [yswery/PHP-DNS-SERVER#11]
Currently (especially if the recursive provider is used) the DNS server can only handle one request at a time.

**Comment by ivanstan** [comment]
ReactPHP would be great for this

**Comment by ivanstan** [comment]
@yswery @codenamegary can you guys check this branch. I managed to make it work

https://github.com/ivanstan/PHP-DNS-SERVER/commit/aa924cf0ac6d689e41d64dfaa56f1f136e75bba7

**Comment by yswery** [comment]
Fixed in PR #46 Epic work @ivanstan
