### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by samuelwilliams** [yswery/PHP-DNS-SERVER#17]
What license is this released under?

**Comment by codenamegary** [comment]
I submitted a PR with the MIT license included. Will be up to @yswery to decide to accept it or not.

**Comment by codenamegary** [comment]
@samuelwilliams - Actually, it is already MIT licensed.

https://github.com/yswery/PHP-DNS-SERVER/blob/master/composer.json#L9

**Comment by yswery** [comment]
Sorry missed this totally. Its an MIT licensed yep
