### ISSUE TITLE
Local filesystem provider

### ISSUE THREAD

**Issue by Muffinman** [yswery/PHP-DNS-SERVER#38]
Hi,

Just thought you might like to know that I've forked and added support for local filesystem lookups.

e.g. `host -a dev.example.com 127.0.0.1` could check to see if `/path/to/example.com` exists locally and return 127.0.0.1 if found.

It can also be configured to work with domain suffixes e.g. `example.com.dev` or `example.com.localhost`

I'm finding this useful for local web development as I don't need to keep editing my hosts file every time I work on a new site, providing my folder structure is consistent.

Wasn't sure if that functionality was within the scope of this project so I didn't want to open as a PR.

https://github.com/Muffinman/PHP-DNS-SERVER/blob/master/src/DirStorageProvider.php

**Comment by codenamegary** [comment]
That is clever and it looks really good! You should open a PR.

**Comment by codenamegary** [comment]
I believe that's entirely due to this change in Chrome, specific to the ".dev" TLD.

https://laravel-news.com/chrome-63-now-forces-dev-domains-https

This will probably still work fine if you use .local or something along those lines.

**Comment by Muffinman** [comment]
Not in my case, my local domain formats are **dev.example.com** so that my password manager picks up the correct passwords for the parent domain.

It really did seem random where it would work for some domains but not others, and then would randomly stop working all together.

I'm pretty sure it was something specific to Chrome as any `dig` / `host` lookups worked perfectly from the command line, as did Safari when I tested that.
