### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by tterranigma** [yswery/PHP-DNS-SERVER#49]
A recent changes to the class names broke on of my applications. I have some ansible scripts that pull php-dns-server from github and provision a dns server on a machine of mine. I do this regularly. A few days ago, the dns servers failed to start and the reason was that my `dns.php` script contained the old class names. If there were versions, I could pull the specified version without fear of future breaks.

**Comment by ivanstan** [comment]
True, we need tagged versions

**Comment by samuelwilliams** [comment]
I have tagged the latest commit (680f711) with an initial version of 0.1. Additionally, there is now a changelog to update on each version.
