### ISSUE TITLE
Check if port is in use

### ISSUE THREAD

**Issue by ivanstan** [yswery/PHP-DNS-SERVER#63]
I was working on server while in background another instance was started listening on same port (UDP 53). This caused script to finish without showing me any info. It took me a while to discover what was the problem. We should check if port is in user before calling `$loop->run()` and throw exception.

**Comment by samuelwilliams** [comment]
Diving into React's code, it looks like it should be throwing an error if a port is in use, but it doesn't seem to. But in anycase, think this is something to put on whoever is implementing the project.
