### ISSUE TITLE
Don't fail on unsupported dns records

### ISSUE THREAD

**Issue by tterranigma** [yswery/PHP-DNS-SERVER#74]
I took a quick a look in the code after #73. Comparing [dns_answer_names](https://github.com/yswery/PHP-DNS-SERVER/blob/master/src/RecursiveResolver.php#L12) and [dns query type](https://github.com/yswery/PHP-DNS-SERVER/blob/master/src/RecordTypeEnum.php#L11), it seems to me that if a query of a type missing from `dns_answer_names` (like the `SRV` record that caused #73) is received, php-dns will crash on the same point as in #73. 

I think that php-dns should not fail in any case. If my understanding above is correct, how could php-dns handle that situation more gracefully?

**Comment by samuelwilliams** [comment]
Check out branch `version-1` - this has a much more graceful way of dealing with unsupported record types.

**Comment by tterranigma** [comment]
This seems like a total reworking of the project structure. Does this mean that #73 is useless? Should I close it?

**Comment by samuelwilliams** [comment]
Dont close it, it's still an improvement. But I haven't worked in SRV RData
into version-1 yet.
