### ISSUE TITLE
Support for OPT RR type

### ISSUE THREAD

**Issue by tterranigma** [yswery/PHP-DNS-SERVER#78]
I am a bit confused regarding support for the `OPT` RR type. As mentioned [here](https://github.com/yswery/PHP-DNS-SERVER/blob/6dce8906766407dd074f646cad4f365394fa4b27/src/Tests/ServerTest.php#L106) it is not supported. On the README however it mentions `OPT` under the supported types. Is it mentioned there falsely?

**Comment by samuelwilliams** [comment]
I have removed it from the README. There is no specific support for EDNS built-in ATM

**Comment by tterranigma** [comment]
Thanks for the clarification. I am closing this in favor of #52 .
