### ISSUE TITLE
example.php does not fail if run without privileges

### ISSUE THREAD

**Issue by tterranigma** [yswery/PHP-DNS-SERVER#79]
If you try to run `php examples/example.php` in a fresh `git clone` of the project, the command returns and the exit code is 0. However, no server starts running in the background. If, however, `sudo php examples/example.php` is given instead, the server loop is started successfully. It would be useful to output either an error message or return with a non-zero exit code.

**Comment by samuelwilliams** [comment]
@tterranigma - Does PR #84 solve the issue you've reported here?

**Comment by tterranigma** [comment]
Almost, I think. There is an error message but the exit code is 0. Shouldn't it be at at least 1?

**Comment by raheelkhan** [comment]
@tterranigma I have pushed the code that returns exit code 1 if there is any ServerExceptionEvent raised. Please verify. Thanks

**Comment by raheelkhan** [comment]
Can we close this against PR #84 ?
