### ISSUE TITLE
Any plan to update dependencies?

### ISSUE THREAD

**Issue by asalisaf** [yswery/PHP-DNS-SERVER#87]
Hello,
I am currently using latest version of react/socket and have issue with installing package.
Do you have any plan to update the version of React?
Thanks

**Comment by samuelwilliams** [comment]
I think it would be a good idea to update. Did you want to make a PR for us to review?

**Comment by asalisaf** [comment]
Yes! I will work on it soon:)

**Comment by samuelwilliams** [comment]
Updated.
