### ISSUE TITLE
CNAME NOT WORK

### ISSUE THREAD

**Issue by samukca** [yswery/PHP-DNS-SERVER#89]
In the request www.host.domain the server searches for record type A instead of CNAME

Ex.
info: Answer: www.googleapis.com. A IN 000.000.000.000

**Comment by xaoseric** [comment]
will look into this, and see if it can be patched for the next release

**Comment by samuelwilliams** [comment]
Hi @samukca 
Thanks for the issue. Can you please detail configuration and zones that you used that produced the error, this will help with identifying the issue.
Thanks!
