### ISSUE TITLE
Make meaningful inheritance possible, change private properties to protected

### ISSUE THREAD

**Issue by ampaze** [yswery/PHP-DNS-SERVER#92]
I want to inherit from `DNS\Server` and add a `stop` method, which is not possible as `$loop` and all other properties are private. Can this be changed? I could make a PR if needed.

**Comment by samuelwilliams** [comment]
Hi, send through a PR changing the methods that you need access to.

**Comment by ampaze** [comment]
Done. #93

**Comment by ampaze** [comment]
Thanks!

**Comment by ampaze** [comment]
Could you also make a new release?

Even using https://packagist.org/packages/yswery/dns#dev-master is not up to date.
