### ISSUE TITLE
Could you make a new release available via composer

### ISSUE THREAD

**Issue by ampaze** [yswery/PHP-DNS-SERVER#96]

**Comment by samuelwilliams** [comment]
Hi @ampaze 
[Version 1.4 has just been released](https://github.com/yswery/PHP-DNS-SERVER/releases/tag/v1.4)

**Comment by ampaze** [comment]
Awesome!

It is not yet visible at
https://packagist.org/packages/yswery/dns

**Comment by samuelwilliams** [comment]
I'm not sure why, it may have something to do with the settings on packagist or github. Bump @yswery

**Comment by samuelwilliams** [comment]
Disregard, there's a button on the packagist website... Packagist is now synced

**Comment by ampaze** [comment]
Thanks.
Version 1.4 unexpectedly requires Symfony 5, I posted a comment in the pertaining PR
https://github.com/yswery/PHP-DNS-SERVER/pull/99#issuecomment-597016273
